### PR TITLE
Some minor improvements

### PR DESCRIPTION
**Pull request by Fireboyd78**
## Changes made
1. Now using NuGet packages for the projects instead of relying on the (missing) DLL's in the "other" folder.
2. Added missing Gibbed.Squish DLL files. This also required removing `*.dll` from the ignore list.
3. Added customizable "Bytes per Row" option for the Raw Viewer. Sometimes 16-bytes per row just doesn't cut it when you're looking at hex :P
4. Made a couple of minor changes to ArchiveHeader, mostly involving some comments and the credit attribution to yours truly.

On a side note, thank you for giving me credit. I'm glad I could help out, and hopefully I will have more to offer in the future. This project is definitely a good starting point!

### CODE REVIEW

**Comment by Fireboyd78** [comment]
@MartinJK Are you still working on this?

**Comment by Fireboyd78** [comment]
@MartinJK I take it this project has been abandoned? Shame...

**Comment by MartinJK** [comment]
Hey, first of all, thanks for your contribution! Feel free adding yourself to the credits :)

About project abandonation: I'm quite busy at the moment, also I haven't found time to look deeper into's mafia 3 file system. I'm afraid I cannot tell you when I'm going to have time for it..

**Comment by Fireboyd78** [comment]
No problem, I understand. Apologies for being rude about abandoning the project!

**Pull request merged**
